### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by anselm-urban** [peternerlich/IsoPix#1]
Fonts are not displayed correctly because Ubuntu´s system font is used. I´d suggest using a system font stack so that the app feels native: 
font-family: -apple-system, “Oxygen”, “Ubuntu”, “Roboto”, “Segoe UI”, “Helvetica Neue”, “Lucida Grande”, sans-serif;
Read more about it here: https://medium.com/@mwichary/system-shock-6b1dc6d6596f

**Comment by PeterNerlich** [comment]
Using `font-family: "Ubuntu", -apple-system, "Oxygen", "San Francisco", "Roboto", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif;` now

**Comment by anselm-urban** [comment]
You should leave out "San Francisco" (Apple´s system font). The declaration "-apple-system" already refers to San Francisco and makes the font responsive to the font-size used. If you declare San Francisco, only the regular font is used, so it loses its smart capabilities. The article on Medium is wrong on this topic.

**Comment by PeterNerlich** [comment]
Thank you, done that.
